apiVersion: v1
kind: ReplicationController
metadata:
  name: rc
spec:
  replicas: 3
  # selector:
  #   app: myapp
  template:
    metadata:
      name: template
      labels:
        app: label
    spec:
      containers:
        - name: nginx1
          image: nginx
          ports:
            - containerPort: 80
